### ISSUE TITLE
download button probleme

### ISSUE THREAD

**Issue by DonOpeAI** [muratozturk5/OpenAI-Dall-E-2#2]
please help the button download don t do nothing when click in it

**Comment by muratozturk5** [comment]
Hi, did you grand permisson when app is launched it asking for storage permission, if you didn't grand permisson download button wont work

**Comment by muratozturk5** [comment]
let me know if you tried

**Comment by DonOpeAI** [comment]
it don't give me the permission for storage

**Comment by muratozturk5** [comment]
okay, can you try to grant permission  from Settings -> Apps -> OpenAI -> Permissions -> Storage , let me know after that

**Comment by DonOpeAI** [comment]
i already go to setting but they say permissions not requested and i can t click in it

**Comment by muratozturk5** [comment]
can you share your phone informations and an screenshot in app setting page ?

**Comment by DonOpeAI** [comment]
![Screenshot 2023-01-02 132204](https://user-images.githubusercontent.com/121756369/210278843-44b6628b-4b04-4092-a61f-0665f4962e82.png)

**Comment by muratozturk5** [comment]
can you uninstall app from device and install it from android studio ? after that try to press download button, and take a screenshot from logcat. thank you.

**Comment by DonOpeAI** [comment]
its a screenshot from the android studio

**Comment by DonOpeAI** [comment]
![Screenshot 2023-01-02 133109](https://user-images.githubusercontent.com/121756369/210279284-396b6499-d0dc-4028-8565-0da5c57bf9b3.png)

**Comment by muratozturk5** [comment]
did you take that after pressed download button ?

**Comment by DonOpeAI** [comment]
yes, every time i click download i get this

**Comment by muratozturk5** [comment]
it's not an error, should be diffrent error , you re using physical device or emulator ?

**Comment by DonOpeAI** [comment]
emulator, is the download button working good in your device

**Comment by muratozturk5** [comment]
yes of course working in many devices that i have tried, could you try to run app in physical device?

**Comment by DonOpeAI** [comment]
i try buy nothing , in the setting when i click permission i don t see any permission to activate in the physical device

**Comment by DonOpeAI** [comment]
is there any other method to make the download button working like deleting this method and using another

**Comment by muratozturk5** [comment]
I will try today if i make change i will text here

**Comment by muratozturk5** [comment]
i have made a changes about it and i have fixed, good luck
